### ISSUE TITLE
Vertices on models bugging out

### ISSUE THREAD

**Issue by Demez** [quiverteam/Engine#22]
Don't think I need to explain this one.

![2019-05-10_16-37-29_quiver_HALF-LIFE_2](https://user-images.githubusercontent.com/30940677/57555393-29edd900-7342-11e9-832e-53d61bca8dee.jpg)

**Comment by Demez** [comment]
This actually is far worse when you use mat_wireframe
![2019-05-11_18-31-40_quiver_HALF-LIFE_2](https://user-images.githubusercontent.com/30940677/57575585-4a3d9680-741b-11e9-932d-80d33c3137b8.png)

**Comment by JJL772** [comment]
Might be related to the low level libraries like mathlib because it happens somewhat in HLMV.
I would try to build with `USE_STDC_FOR_SIMD` enabled for now. It will slow the game down a bit probably, but it will use more "normal" math functions instead of the custom sine/cosine/etc. functions that return very wrong results when the parameters are out of the first period or so of the function.

**Comment by Demez** [comment]
Fixed in #38
